import { useState } from 'react';
import { LyricsInput } from './LyricsInput';
import { useActor } from '../hooks/useActor';
import { ExternalBlob } from '../backend';
import { toast } from 'sonner';
import { Sparkles } from 'lucide-react';

interface GenerationModeProps {
  voiceSampleId: string;
  onComplete: (requestId: string, lyrics: string) => void;
}

export function GenerationMode({ voiceSampleId, onComplete }: GenerationModeProps) {
  const { actor } = useActor();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleLyricsSubmit = async (lyrics: string) => {
    if (!actor) {
      toast.error('Backend not ready');
      return;
    }

    setIsSubmitting(true);

    try {
      const requestId = `lyrics-${Date.now()}`;
      const userId = 'user-' + Date.now(); // In a real app, this would be the authenticated user ID
      
      // Create a placeholder audio blob for the finalMix parameter
      // In production, this would be generated by the AI processing
      const placeholderAudio = new Uint8Array(1024);
      const finalMix = ExternalBlob.fromBytes(placeholderAudio);
      
      await actor.submitLyricsRequest(requestId, userId, lyrics, voiceSampleId, finalMix);
      
      toast.success('Lyrics submitted! Generating your song...');
      onComplete(requestId, lyrics);
    } catch (err) {
      toast.error('Failed to submit lyrics');
      console.error(err);
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="text-center">
        <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-gradient-to-br from-[oklch(0.65_0.25_280)] to-[oklch(0.55_0.27_260)]">
          <Sparkles className="h-8 w-8 text-white" />
        </div>
        <h2 className="mb-2 text-3xl font-bold">Step 2: Write Your Lyrics</h2>
        <p className="text-muted-foreground">
          Express yourself through words - our AI will compose the music and sing it with your voice
        </p>
      </div>

      <div className="rounded-xl border-2 border-border bg-card p-8 shadow-lg">
        <LyricsInput onSubmit={handleLyricsSubmit} isSubmitting={isSubmitting} />
      </div>

      <div className="rounded-lg bg-muted/50 p-4 text-center text-sm text-muted-foreground">
        <p>💡 Tip: Structure your lyrics with verses, choruses, and bridges for the best results</p>
      </div>
    </div>
  );
}
