/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LyricsStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Text,
});
export const LyricsRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : LyricsStatus,
  'lyrics' : IDL.Text,
  'stylePrompt' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'generatedCoverId' : IDL.Opt(IDL.Text),
  'voiceSampleId' : IDL.Text,
});
export const VoicePersona = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'voiceSampleId' : IDL.Text,
});
export const ModeType = IDL.Variant({
  'cover' : IDL.Null,
  'original' : IDL.Null,
});
export const Song = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioFile' : ExternalBlob,
  'creationDate' : IDL.Int,
  'instrumentalFile' : ExternalBlob,
  'artist' : IDL.Text,
  'modeType' : ModeType,
  'voiceSampleId' : IDL.Opt(IDL.Text),
});
export const VoiceSample = IDL.Record({
  'id' : IDL.Text,
  'voiceFile' : ExternalBlob,
  'userId' : IDL.Text,
});
export const Cover = IDL.Record({
  'id' : IDL.Text,
  'originalSong' : Song,
  'userVoice' : VoiceSample,
  'finalMix' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createCover' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'createVoicePersona' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllLyricsRequests' : IDL.Func([], [IDL.Vec(LyricsRequest)], ['query']),
  'getAllVoicePersonas' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VoicePersona)],
      ['query'],
    ),
  'getCover' : IDL.Func([IDL.Text], [IDL.Opt(Cover)], ['query']),
  'getLyricsRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LyricsRequest)],
      ['query'],
    ),
  'getUserLibrary' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'submitLyricsRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'uploadSong' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        ExternalBlob,
        IDL.Opt(IDL.Text),
        ModeType,
      ],
      [],
      [],
    ),
  'uploadVoiceSample' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LyricsStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Text,
  });
  const LyricsRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : LyricsStatus,
    'lyrics' : IDL.Text,
    'stylePrompt' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'generatedCoverId' : IDL.Opt(IDL.Text),
    'voiceSampleId' : IDL.Text,
  });
  const VoicePersona = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'voiceSampleId' : IDL.Text,
  });
  const ModeType = IDL.Variant({ 'cover' : IDL.Null, 'original' : IDL.Null });
  const Song = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioFile' : ExternalBlob,
    'creationDate' : IDL.Int,
    'instrumentalFile' : ExternalBlob,
    'artist' : IDL.Text,
    'modeType' : ModeType,
    'voiceSampleId' : IDL.Opt(IDL.Text),
  });
  const VoiceSample = IDL.Record({
    'id' : IDL.Text,
    'voiceFile' : ExternalBlob,
    'userId' : IDL.Text,
  });
  const Cover = IDL.Record({
    'id' : IDL.Text,
    'originalSong' : Song,
    'userVoice' : VoiceSample,
    'finalMix' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createCover' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'createVoicePersona' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllLyricsRequests' : IDL.Func([], [IDL.Vec(LyricsRequest)], ['query']),
    'getAllVoicePersonas' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VoicePersona)],
        ['query'],
      ),
    'getCover' : IDL.Func([IDL.Text], [IDL.Opt(Cover)], ['query']),
    'getLyricsRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LyricsRequest)],
        ['query'],
      ),
    'getUserLibrary' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'submitLyricsRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'uploadSong' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          ModeType,
        ],
        [],
        [],
      ),
    'uploadVoiceSample' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };