/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cover {
  'id' : string,
  'originalSong' : Song,
  'userVoice' : VoiceSample,
  'finalMix' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface LyricsRequest {
  'id' : string,
  'status' : LyricsStatus,
  'lyrics' : string,
  'stylePrompt' : [] | [string],
  'userId' : string,
  'generatedCoverId' : [] | [string],
  'voiceSampleId' : string,
}
export type LyricsStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'processing' : null } |
  { 'failed' : string };
export type ModeType = { 'cover' : null } |
  { 'original' : null };
export interface Song {
  'id' : string,
  'title' : string,
  'audioFile' : ExternalBlob,
  'creationDate' : bigint,
  'instrumentalFile' : ExternalBlob,
  'artist' : string,
  'modeType' : ModeType,
  'voiceSampleId' : [] | [string],
}
export interface VoicePersona {
  'id' : string,
  'userId' : string,
  'name' : string,
  'voiceSampleId' : string,
}
export interface VoiceSample {
  'id' : string,
  'voiceFile' : ExternalBlob,
  'userId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'completeLyricsRequest' : ActorMethod<[string, ExternalBlob], undefined>,
  'createCover' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'createVoicePersona' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'getAllLyricsRequests' : ActorMethod<[], Array<LyricsRequest>>,
  'getAllVoicePersonas' : ActorMethod<[string], Array<VoicePersona>>,
  'getCover' : ActorMethod<[string], [] | [Cover]>,
  'getLyricsRequest' : ActorMethod<[string], [] | [LyricsRequest]>,
  'getUserLibrary' : ActorMethod<[string], Array<Song>>,
  'submitLyricsRequest' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'uploadSong' : ActorMethod<
    [
      string,
      string,
      string,
      ExternalBlob,
      ExternalBlob,
      [] | [string],
      ModeType,
    ],
    undefined
  >,
  'uploadVoiceSample' : ActorMethod<[string, string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];