/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VoicePersona {
    id: string;
    userId: string;
    name: string;
    voiceSampleId: string;
}
export interface VoiceSample {
    id: string;
    voiceFile: ExternalBlob;
    userId: string;
}
export interface LyricsRequest {
    id: string;
    status: LyricsStatus;
    lyrics: string;
    stylePrompt?: string;
    userId: string;
    generatedCoverId?: string;
    voiceSampleId: string;
}
export interface Cover {
    id: string;
    originalSong: Song;
    userVoice: VoiceSample;
    finalMix: ExternalBlob;
}
export interface Song {
    id: string;
    title: string;
    audioFile: ExternalBlob;
    creationDate: bigint;
    instrumentalFile: ExternalBlob;
    artist: string;
    modeType: ModeType;
    voiceSampleId?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type LyricsStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "complete";
    complete: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "failed";
    failed: string;
};
export enum ModeType {
    cover = "cover",
    original = "original"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    completeLyricsRequest(requestId: string, finalMix: ExternalBlob): Promise<void>;
    createCover(coverId: string, songId: string, voiceSampleId: string, finalMix: ExternalBlob): Promise<void>;
    createVoicePersona(id: string, userId: string, name: string, voiceSampleId: string): Promise<void>;
    getAllLyricsRequests(): Promise<Array<LyricsRequest>>;
    getAllVoicePersonas(userId: string): Promise<Array<VoicePersona>>;
    getCover(id: string): Promise<Cover | null>;
    getLyricsRequest(requestId: string): Promise<LyricsRequest | null>;
    getUserLibrary(userId: string): Promise<Array<Song>>;
    submitLyricsRequest(requestId: string, userId: string, lyrics: string, voiceSampleId: string, stylePrompt: string | null): Promise<void>;
    uploadSong(id: string, title: string, artist: string, audioFile: ExternalBlob, instrumentalFile: ExternalBlob, voiceSampleId: string | null, modeType: ModeType): Promise<void>;
    uploadVoiceSample(id: string, userId: string, voiceFile: ExternalBlob): Promise<void>;
}
import type { Cover as _Cover, ExternalBlob as _ExternalBlob, LyricsRequest as _LyricsRequest, LyricsStatus as _LyricsStatus, ModeType as _ModeType, Song as _Song, VoiceSample as _VoiceSample, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async completeLyricsRequest(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLyricsRequest(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLyricsRequest(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCover(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCover(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCover(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createVoicePersona(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVoicePersona(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVoicePersona(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllLyricsRequests(): Promise<Array<LyricsRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLyricsRequests();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLyricsRequests();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVoicePersonas(arg0: string): Promise<Array<VoicePersona>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVoicePersonas(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVoicePersonas(arg0);
            return result;
        }
    }
    async getCover(arg0: string): Promise<Cover | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCover(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCover(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLyricsRequest(arg0: string): Promise<LyricsRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLyricsRequest(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLyricsRequest(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserLibrary(arg0: string): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLibrary(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLibrary(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLyricsRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLyricsRequest(arg0, arg1, arg2, arg3, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLyricsRequest(arg0, arg1, arg2, arg3, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async uploadSong(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: ExternalBlob, arg5: string | null, arg6: ModeType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadSong(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg5), to_candid_ModeType_n28(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadSong(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg5), to_candid_ModeType_n28(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadVoiceSample(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVoiceSample(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVoiceSample(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_Cover_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cover): Promise<Cover> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LyricsRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LyricsRequest): LyricsRequest {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_LyricsStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LyricsStatus): LyricsStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ModeType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModeType): ModeType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Song_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Song): Promise<Song> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_VoiceSample_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceSample): Promise<VoiceSample> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cover]): Promise<Cover | null> {
    return value.length === 0 ? null : await from_candid_Cover_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LyricsRequest]): LyricsRequest | null {
    return value.length === 0 ? null : from_candid_LyricsRequest_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _LyricsStatus;
    lyrics: string;
    stylePrompt: [] | [string];
    userId: string;
    generatedCoverId: [] | [string];
    voiceSampleId: string;
}): {
    id: string;
    status: LyricsStatus;
    lyrics: string;
    stylePrompt?: string;
    userId: string;
    generatedCoverId?: string;
    voiceSampleId: string;
} {
    return {
        id: value.id,
        status: from_candid_LyricsStatus_n12(_uploadFile, _downloadFile, value.status),
        lyrics: value.lyrics,
        stylePrompt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.stylePrompt)),
        userId: value.userId,
        generatedCoverId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.generatedCoverId)),
        voiceSampleId: value.voiceSampleId
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    originalSong: _Song;
    userVoice: _VoiceSample;
    finalMix: _ExternalBlob;
}): Promise<{
    id: string;
    originalSong: Song;
    userVoice: VoiceSample;
    finalMix: ExternalBlob;
}> {
    return {
        id: value.id,
        originalSong: await from_candid_Song_n18(_uploadFile, _downloadFile, value.originalSong),
        userVoice: await from_candid_VoiceSample_n23(_uploadFile, _downloadFile, value.userVoice),
        finalMix: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.finalMix)
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    audioFile: _ExternalBlob;
    creationDate: bigint;
    instrumentalFile: _ExternalBlob;
    artist: string;
    modeType: _ModeType;
    voiceSampleId: [] | [string];
}): Promise<{
    id: string;
    title: string;
    audioFile: ExternalBlob;
    creationDate: bigint;
    instrumentalFile: ExternalBlob;
    artist: string;
    modeType: ModeType;
    voiceSampleId?: string;
}> {
    return {
        id: value.id,
        title: value.title,
        audioFile: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.audioFile),
        creationDate: value.creationDate,
        instrumentalFile: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.instrumentalFile),
        artist: value.artist,
        modeType: from_candid_ModeType_n21(_uploadFile, _downloadFile, value.modeType),
        voiceSampleId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.voiceSampleId))
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    voiceFile: _ExternalBlob;
    userId: string;
}): Promise<{
    id: string;
    voiceFile: ExternalBlob;
    userId: string;
}> {
    return {
        id: value.id,
        voiceFile: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.voiceFile),
        userId: value.userId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    complete: null;
} | {
    processing: null;
} | {
    failed: string;
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "complete";
    complete: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "failed";
    failed: string;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "complete" in value ? {
        __kind__: "complete",
        complete: value.complete
    } : "processing" in value ? {
        __kind__: "processing",
        processing: value.processing
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cover: null;
} | {
    original: null;
}): ModeType {
    return "cover" in value ? ModeType.cover : "original" in value ? ModeType.original : value;
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Song>): Promise<Array<Song>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Song_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LyricsRequest>): Array<LyricsRequest> {
    return value.map((x)=>from_candid_LyricsRequest_n10(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ModeType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModeType): _ModeType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModeType): {
    cover: null;
} | {
    original: null;
} {
    return value == ModeType.cover ? {
        cover: null
    } : value == ModeType.original ? {
        original: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
